baseURL = "https://irons163.github.io"
languageCode = "en-us"
title = "go-ethereum"
theme = "hyde-hyde"
pygmentsStyle="autumn"
pygmentsCodeFences=true
[[menu.main]]
    name = "Post"
    identifier = "post"
    weight = 30
    url = "/post/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 30
    url = "/portfolio/"
[params.social]
    github = "irons163"
    facebook = "100000231660391"
    email = "irons163"
[params]
    authorimage = "/aaa.jpg"
    
