baseURL = "https://irons163.github.io/"
languageCode = "en-us"
title = "go-ethereum"
theme = "hyde-hyde"
pygmentsStyle="autumn"
pygmentsCodeFences=true
[[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 10
    url = "/post/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 20
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 30
    url = "/about/"
[params.social]
    github = "irons163"
    facebook = "100000231660391"
    email = "irons163"
[params]
    authorimage = "/aaa.jpg"
    mainSections = ["post"]
    
